### ISSUE TITLE
Failing integration test: Integration.Commands.ChartApiTests.GetTopArtists_Success

### ISSUE THREAD

**Issue by rikkit** [inflatablefriends/lastfm#114]
https://ci.appveyor.com/project/rikkit/lastfm/build/1.0.999.323/tests

Error message:

```
  Expected: 30
  But was:  60
```

Error stack trace:

```
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at IF.Lastfm.Core.Tests.Integration.Commands.ChartApiTests.<GetTopArtists_Success>d__3.MoveNext() in C:\projects\lastfm\src\IF.Lastfm.Core.Tests.Integration\Commands\ChartGetTopTagsTests.cs:line 40
   at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
```

**Comment by th0mk** [comment]
While the integration tests can be useful, I'm not sure if its a good idea to include them in the build pipeline. Tests like these are pretty sensitive since they use real data and not mock data.

Also not sure if it's a good idea to have api key/secrets in the repo, but that's a different issue.
